baseURL = 'https://www.aiwrite.online/'
languageCode = 'zh-cn'
title = 'Clinical Education Insights'
theme = 'ananke'
timeZone = "Asia/Shanghai"

[params]
  mainSections = ["posts"]

[menu]
  [[menu.main]]
    identifier = "home"
    name = "首页"
    url = "/"
    weight = 1
