baseURL = 'https://www.aiwrite.online/'
languageCode = 'zh-cn'
title = 'Clinical Education Insights'
theme = 'mainroad'
timeZone = "Asia/Shanghai"
paginate = 10

[Author]
  name = "Dr. Ma"
  bio = "专注临床医学教育研究与实践"

[Params]
  description = "临床医学教育研究洞见 | 基础内容 · 研究方法 · 策略分享"
  copyright = "Clinical Education Insights"
  opengraph = true
  twitter_cards = true
  readmore = true
  authorbox = true
  toc = true
  pager = true
  post_meta = ["author", "date", "categories"]
  mainSections = ["posts"]
  dateformat = "2006-01-02"
  mathjax = true

[Params.sidebar]
  home = "right"
  list = "right"
  single = "right"
  widgets = ["search", "recent", "categories", "taglist", "social"]

[Params.widgets]
  recent_num = 5

[Params.widgets.social]
  email = "mataoran@gmail.com"
  # github = "your-github-username" 
  # twitter = "your-twitter-username"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "首页"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "about"
    name = "关于我们"
    url = "/about/"
    weight = 2
  [[menu.main]]
    identifier = "privacy"
    name = "隐私政策"
    url = "/privacy/"
    weight = 3
